name: test

on:
  push:
    branches: [ "main" ]

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0'
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo run